Fetching the books from the API
cristinarangoe/library-project pull request #3
Opened 2023-04-25 20:16 UTC by cristinarangoe

- Fetch para traer los libros por la categoría que escoja el usuario en el dropdown
- Fetch para traer los libros según la búsqueda que haga el usuario 
- Un dropdown en la barra de búsqueda para que el usuario escoja como quiere hacer la búsqueda (todo, titulo, autor o categoría)
- Fetch para que me traiga un libro en específico
- Arreglos en la UI
- Todos los fetch ya están incorporados en la UI, es decir, que los libros que salen son los que me trae la API
- Paginación incorporada
- Dropdown en la página de resultados para que el usuario escoja la cantidad de libros que quiere ver en el resultado (5,10,15,20)

2023-05-04 22:19 UTC, Atabord requested changes

2023-05-04 22:19 UTC, Atabord commented on src/components/Header/SearchBar.jsx
> +            return opt === "Todos" ? (
creo que hay un bug aquí, sería opt.name === "Todos"

2023-05-04 22:19 UTC, Atabord commented on src/components/Header/SearchBar.jsx
> +          {
mm creo que este { sobra

2023-05-04 22:19 UTC, Atabord commented on src/components/Header/SearchBar.jsx
> +      <div className={styles["nav-searchbar-dividor"]} />
no se como se vea esto en la vida real, pero en caso de ser un divisor horizontal puedes usar un `<hr />`

2023-05-04 22:19 UTC, Atabord commented on src/components/Header/SubjectsList.jsx
>          <li key={index} className={styles["main-nav-ppal-dropdown-option"]}>
no es buena practiva usar el index como el key, lo que puedes hacer es usar el mismo id de los subjects

2023-05-04 22:19 UTC, Atabord commented on src/components/Main/BookList.jsx
> +  books: PropTypes.array,
sugerencia: usualmente cuando hay arreglos u objetos usamos ArrayOf y Shape, el arrayOf es para indicar que tipo de datos hay en el arreglo, y el shape es para indicar que es un objeto con ciertos atributos

2023-05-04 22:19 UTC, Atabord commented on src/pages/BookDetail.jsx
> +      const response = await fetch(
sugerencia: probablemente por la implementación de redux ya hayas cambiado esto pero igual me gustaría dejar la sugerencia, es buena práctica tener depronto un archivo de utilidades que se encargue de hacer estos llamados a servicio a fin de reducir el código que se escribe dentro del componente desde el componente simplemente llamas esa utilidad, y asignas los valores o los errores al state

otra posibilidad es hacer un customHook para los fetchs

2023-05-04 22:19 UTC, Atabord commented on src/pages/BookDetail.jsx
> +      const transformedBook = {
una buena práctica de código limpio sería tener una funcion externa que se encargue de hacer la transformación y retornarla, con la unica función de mantener separados los niveles de abstracción

2023-05-04 22:19 UTC, Atabord commented on src/pages/BookListBySearch.jsx
> +      const response = await fetch(
suggestion: misco comentario, si es posible, pasar a una funcion de utilidades o a un custom hook

2023-05-04 22:19 UTC, Atabord commented on src/pages/BooksListBySubject.jsx
> +    <div className={styles["book-list-ppal"]}>
Veo que este componente tienen los mismos componentes hijos que el BookListBySearch, para evitar duplicados tienes 2 opciones:
1. tener 2 componentes cada uno usa un useffect diferente pero llama a 1 componente hijo reusable que tiene esta misma estructura
2. tener 1 solo componente que llame a un servicio diferente dependiendo de la ruta en la que esta

2023-05-05 14:35 UTC, cristinarangoe commented on src/components/Header/SearchBar.jsx
> +      <div className={styles["nav-searchbar-dividor"]} />
Es un divisor pero vertical, por lo que no podía usar <hr/>, si no que tuve que hacer un div para eso. O hay alguna otra manera de hacerlo?

2023-05-06 01:58 UTC, Atabord commented on src/components/Header/SearchBar.jsx
> +      <div className={styles["nav-searchbar-dividor"]} />
mm no, esta bien, la otra opción es usar border en el select

2023-05-06 02:39 UTC, Atabord requested changes

2023-05-06 02:39 UTC, Atabord commented on src/pages/BooksListBySubject.jsx
> +  //   setIsLoading(true);
Recuerda eliminar el código comentado :)

2023-05-09 01:40 UTC, Atabord approved these changes

2023-05-09 14:08 UTC, merged