Adding redux for pagination and saving favorite books to local storage
cristinarangoe/library-project pull request #4
Opened 2023-05-09 15:35 UTC by cristinarangoe

- Se adicionó Redux para toda la paginación (tanto para el dropdown en donde el usuario puede escoger el número de libros por página y para la paginación inferior, donde se puede ir a la página deseada)
- Se creó la funcionalidad para adicionar y remover libros favoritos al local storage.
- Se adicionó Redux para la funcionalidad de libros favoritos

2023-06-01 20:18 UTC, Atabord requested changes

2023-06-01 20:18 UTC, Atabord commented on src/components/Main/BookItem.jsx
> +          {props.book.coverUrl && (
sugerencia: tambien podrías usar un ternary
props.book.coverUrl ? ... : ...

2023-06-01 20:18 UTC, Atabord commented on src/components/Main/BookItem.jsx
> +          value={props.book.id}
pregunta: para que necesitas este key y este value?

2023-06-01 20:18 UTC, Atabord commented on src/utils/searchBarDropdownOptions.js
> +const optionsDropdown = [
usualmente las constantes se ponen en una carpeta de constantes, la de utils suele ser para funciones

2023-06-01 20:18 UTC, Atabord commented on src/utils/subjectsList.js
> +const subjectsLists = [
usualmente las constantes se ponen en una carpeta de constantes, la de utils suele ser para funciones

2023-06-01 20:18 UTC, Atabord commented on src/components/Main/BookList.jsx
> +            <BookItem book={book} key={book.id} isFavorite={false} />
sugerencia: aqui lo que puedes hacer es tener solo un BookItem pero en la propiedad pasas el valor de isAFavoriteBook en isFavorite 
`isFavorite={ isAFavoriteBook }`

2023-06-01 20:18 UTC, Atabord commented on src/pages/BookDetail.jsx
> +      const favorites = JSON.parse(localStorage.getItem("favoriteBooks"));
sugerencia, puedes mover esta linea antes de la linea 33 y en la linea 33 preguntas if (favorites) asi evitas llamar el getItem 2 veces

2023-06-01 20:18 UTC, Atabord commented on src/pages/BookDetail.jsx
> +        {!book.coverUrl && (
mm este codigo me parece conocido, crees que hay alguna forma de crear un componente y reutilizar este codigo para que no tengas que duplicarlo en varios lugares (me refiero al de usar la imagen del libro si existe y sino usar el default)

2023-06-01 20:18 UTC, Atabord commented on src/pages/BookListBySearch.jsx
> +    <div>
no es buena práctica usar divs vacíos, si no es para agregar algun classname, usa Fragments (<>) o algún tag semantico (main, section, etc) dependiendo de las necesidades

2023-06-01 20:18 UTC, Atabord commented on src/pages/BooksListBySubject.jsx
> +    <div>
mismo comentario, si no tienes que agreagar clases, mejor usar Fragment o algun otro tag más semántico

2023-06-01 20:18 UTC, Atabord commented on src/pages/Home.jsx
> +    <div>
same here :)

2023-06-01 20:18 UTC, Atabord commented on src/store/favoriteBooks.jsx
> +    saveFavoriteBooks(state, action) {
pregunta: no deberías tener tambien uno para eliminar favoritebooks?

2023-06-01 20:36 UTC, cristinarangoe commented on src/store/favoriteBooks.jsx
> +    saveFavoriteBooks(state, action) {
La función que se llama saveFavoriteBooks, funciona para agregar y para eliminar el libro favorito. Si ves en la función, al principio se pregunta si el book existe.
1. Si existe: se filtra el arreglo, eliminando el libro favorito (porque ya no es favorito)
2. No existe: se hace push al arreglo de libros con el nuevo libro favorito

Y al final, ya se hace el set en el local storage el arreglo de libros

La función de setFavoriteBooks es para tener actualizado ese arreglo de los libros favoritos, es decir, que siempre que se haga alguna modificación en el local storage, ese arreglo (que es un estado del store) esté actualizado

2023-06-01 20:53 UTC, cristinarangoe commented on src/components/Main/BookItem.jsx
> +          value={props.book.id}
El key no lo necesito, pero el value si lo necesito, para que cuando se presione el botón, me pueda enviar en el evento, el value para saber el id del libro que estoy metiendo en favoritos. Arriba en la función que se llama saveFavoriteBookClickHandler puedes ver que uso e.target.value para meter en favoritos el id del libro

2023-06-01 22:42 UTC, Atabord commented on src/components/Main/BookItem.jsx
> +          value={props.book.id}
ah entiendo, creo que en este caso no sería tan necesario, ya que la función esta dentro del mismo componente si usas `dispatch(favoriteBooksActions.saveFavoriteBooks(props.book.id));` no creo que necesites el value :)

2023-06-02 17:16 UTC, cristinarangoe commented on src/components/Main/BookItem.jsx
> +          value={props.book.id}
Tienes toda la razón, ya quedo corregido

2023-06-27 22:05 UTC, Atabord requested changes

2023-06-27 22:05 UTC, Atabord commented on src/pages/BookDetail.module.scss
> +// .book-detail-image-no-image {
pregunta: necesitas esté codigo comentado?

2023-06-27 22:05 UTC, Atabord commented on src/components/Main/BookList.jsx
> +          console.log("cristina", isAFavoriteBook)
Hola Cristina :) 
(elimina los console logs que no necesites más :) )

2023-06-27 22:05 UTC, Atabord commented on src/components/Main/BookItem.module.scss
> +// .book-item-image-no-image {
pregunta, este comentario es necesario o ya se puede eliminar?

2023-06-27 22:05 UTC, Atabord commented on src/components/Main/BookList.jsx
> +          return <BookItem book={book} key={book.id} isFavorite={isAFavoriteBook ? true: false} />
sugerencia: no necesitas el ternary operator, mas bien cambias el .find() por un .some() y eso te retorna automaticamente un booleano

2023-06-27 22:05 UTC, Atabord commented on src/pages/BookDetail.jsx
> +      const isAFavoriteBook = favorites.find(
puedes usar un const isFavoriteBook = favorites.some(...)
luego haces setIsFavorite(isFavoriteBook)

2023-06-27 22:05 UTC, Atabord commented on src/pages/BookDetail.jsx
> +    const isAFavoriteBook = favoriteBooks.find((item) => item === book.id);
misma sugerencia de arriba

2023-07-18 21:52 UTC, Atabord commented on src/components/UI/DefaultImage.jsx
> +      <div>
sugerencia: creo que este div vacío no es necesario, podría ser eliminado

2023-07-18 21:52 UTC, Atabord approved these changes

2023-07-18 22:20 UTC, cristinarangoe commented on src/components/UI/DefaultImage.jsx
> +      <div>
Este div, es porque en el estilo que se planteó de la imagen determinada, hay un borde interior el cual es ese div. Ese div está estilizado en el archivo de estilos, pero no con clase si no con div {}, por esta razón lo que hice fue asignarle una clase a ese div y ponerle los estilos a esa clase. Acá te pongo una imagen de como es el estilo de ese div.
![image](https://github.com/cristinarangoe/library-project/assets/56897758/a7d12d39-a3be-4d8d-961d-542fda094377)

2023-07-18 22:35 UTC, merged